### ISSUE TITLE
请问有计划支持WalleQ吗？

### ISSUE THREAD

**Issue by ww1126811502** [MountainDash/nonebot-plugin-send-anything-anywhere#108]
我的新QQbot使用的是walleq：https://github.com/onebot-walle/nonebot_adapter_walleq；
我看SupportedAdapters枚举里是有onebot_v12的

**Comment by AzideCupric** [comment]
那你觉得saa支不支持ob12

**Comment by felinae98** [comment]
如果 walleq 用的是 ob12 的话是支持的

**Comment by AzideCupric** [comment]
walleq 可以使用已经适配的 ob12
