### ISSUE TITLE
OB11Reciept 在某些OB11实现中报错

### ISSUE THREAD

**Issue by lgc2333** [MountainDash/nonebot-plugin-send-anything-anywhere#111]
ref https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/issues/8

**Comment by lgc2333** [comment]
该Issue中使用的OB11实现是`icqq`

**Comment by AzideCupric** [comment]
没有messageid还行，有他的message数据吗

**Comment by lgc2333** [comment]
应该不是没有MessageID，icqq的MessageID好像是一个str

**Comment by lgc2333** [comment]
我让她patch一下看看

**Comment by lgc2333** [comment]
![image](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/59048777/ea33ab4a-c975-459a-8db4-dc7449326c7b)

**Comment by AzideCupric** [comment]
按照[OB11标准](https://github.com/botuniverse/onebot-11/blob/master/event/message.md#%E4%BA%8B%E4%BB%B6%E6%95%B0%E6%8D%AEhttps://github.com/botuniverse/onebot-11/blob/master/event/message.md#%E4%BA%8B%E4%BB%B6%E6%95%B0%E6%8D%AE)，message_id就应该是int吧

https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/event/message.md?plain=1#L17

**Comment by lgc2333** [comment]
确实应该为int，我先close as not planned吧，这个issue可能开的有点冲动
