### ISSUE TITLE
是否应该支持 Receipt 和 MessageId 的联通

### ISSUE THREAD

**Issue by AzideCupric** [MountainDash/nonebot-plugin-send-anything-anywhere#126]
对于这样的一个需要
```python
# 发送第一条消息
receipt = await msg.send(reply=True)
# 回复自己发送的第一条消息
msg = MessageFactory(Reply(...), ...)
```
符合直觉的行为应该是
```python
msg = MessageFactory(Reply(receipt), ...)
```

但就[目前版本](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/releases/tag/v0.4.0)而言,
Reply的构建只能接受 MessageId:

https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/blob/c5892651ba3c87d8bd41de2dbf0cfc808c1a82b1/nonebot_plugin_saa/types/common_message_segment.py#L81-L94

而 MessageId 和 Receipt 之间缺乏了一个链接的桥梁(以OB11为例)
https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/blob/c5892651ba3c87d8bd41de2dbf0cfc808c1a82b1/nonebot_plugin_saa/adapters/onebot_v11.py#L55-L58

https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/blob/c5892651ba3c87d8bd41de2dbf0cfc808c1a82b1/nonebot_plugin_saa/adapters/onebot_v11.py#L160-L171

因此不能很好的构建一个自发送消息的回复, 可行的构建方法可能显得非常丑陋

```python
message_id = MessageId.parse_raw(receipt.dict())
msg = MessageFactory(Reply(message_id))
# 或者
msg = MessageFactory(Reply(OB11MessageId(receipt.message_id))) # 非常平台特化
```
或许 Receipt应该提供一个生成 MessageId 的方法
```python
class Receipt:
	def to_message_id(self, ...) -> MessageId: # ...表示需要补充的参数，或者无
		...
```

**Comment by felinae98** [comment]
Receipt 应该提供一个生成 MessageId 的方法
