### ISSUE TITLE
飞书适配器报错

### ISSUE THREAD

**Issue by blyc** [MountainDash/nonebot-plugin-send-anything-anywhere#138]
https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/blob/e6b81f1ee381193f206a72273748ee8f1c4f7b4d/nonebot_plugin_saa/adapters/feishu.py#L71

https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/blob/e6b81f1ee381193f206a72273748ee8f1c4f7b4d/nonebot_plugin_saa/adapters/feishu.py#L182

![图片](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/34291620/d5ef51d7-d18a-4fbd-9a9f-25d97a46c7f5)
![图片](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/34291620/3cbb7354-3e50-423a-ad83-a57806b52c16)

这两处似乎少解析了一层`data`,又或者因为选择的事件是接受消息v2的原因?
![图片](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/34291620/aaf819e0-3241-4bee-9130-5c34a732ca2c)

**Comment by AzideCupric** [comment]
飞书那边的版本更新了吗？
飞书适配器版本和saa这边限制的匹配吗

**Comment by felinae98** [comment]
@MeetWq 看看？

**Comment by MeetWq** [comment]
飞书适配器 `v2.3.0` 修改了 api 调用方式 https://github.com/nonebot/adapter-feishu/commit/fe1a6ad7ff504162d985d07693b1e0b9e7db833b
我这边改一下
