### ISSUE TITLE
Drop Python 3.8

### ISSUE THREAD

**Issue by AzideCupric** [MountainDash/nonebot-plugin-send-anything-anywhere#155]
follow https://github.com/nonebot/nonebot2/pull/2641

**Comment by felinae98** [comment]
所以我们可以用哪些3.9的语法了。。。

**Comment by AzideCupric** [comment]
https://docs.python.org/3/whatsnew/3.9.html

**Comment by AzideCupric** [comment]
> [docs.python.org/3/whatsnew/3.9.html](https://docs.python.org/3/whatsnew/3.9.html)

没有什么大的变动，主要是typing方面还有语法解析器方面
