### ISSUE TITLE
能否像发送消息一样统一解析传入的消息，例如at数据

### ISSUE THREAD

**Issue by Ljzd-PRO** [MountainDash/nonebot-plugin-send-anything-anywhere#158]
例如用户的命令触发了事件，命令里还at了机器人以外的其他用户，如果可以提供统一的方法获取at信息，会更方便。
其他像图片数据之类的常见数据可能也可以。

**Comment by MeetWq** [comment]
你是否在找 [nonebot-plugin-alconna](https://github.com/nonebot/plugin-alconna)

**Comment by Ljzd-PRO** [comment]
> 你是否在找 [nonebot-plugin-alconna](https://github.com/nonebot/plugin-alconna)

了解了
