### ISSUE TITLE
有大佬知道satori协议的@所有人的motion(id)是什么嘛

### ISSUE THREAD

**Issue by AhBumm** [MountainDash/nonebot-plugin-send-anything-anywhere#159]
`await MessageFactory([Text(msg), Mention(0)]).send_to(TargetQQGroup(group_id=int(gid)))`
使用motion(0)回返回这个
`[9873][05-24 23:13:40][W][CH2131] satori: parser: at 目标 undefined 不带有 id，将跳过该元素。`
小白求助，谢谢大佬

**Comment by AzideCupric** [comment]
参考 adapter-satori 的代码的话

https://github.com/nonebot/adapter-satori/blob/96e60526e5bf76197f04b5732d9ea13a0a7c3d0a/nonebot/adapters/satori/message.py#L77-L79

`at_all`不是通过指定id为某个特别的值实现的，想要使用的话可能需要添加一个新的`MentionAll`才行

**Comment by AhBumm** [comment]
> 参考 adapter-satori 的代码的话
> 
> https://github.com/nonebot/adapter-satori/blob/96e60526e5bf76197f04b5732d9ea13a0a7c3d0a/nonebot/adapters/satori/message.py#L77-L79
> 
> `at_all`不是通过指定id为某个特别的值实现的，想要使用的话可能需要添加一个新的`MentionAll`才行

艹，那感觉这个功能还是挺常用的，有机会更新这个功能嘛。。

**Comment by AzideCupric** [comment]
理论上加起来应该不难 要不要来贡献一下（

**Comment by AhBumm** [comment]
> 理论上加起来应该不难 要不要来贡献一下（

我查了一些文档和源码，但是没有找到at所有人的例子，不知道怎么改。。。或者有没有临时的解决方法，非常感谢

**Comment by AzideCupric** [comment]
要不加个群具体讲讲添加方法（868610060

**Comment by AhBumm** [comment]
通过安装feat/mention-all分支已解决，感谢ac佬的支持
