### ISSUE TITLE
[Proposal] 消息回执相关功能

### ISSUE THREAD

**Issue by felinae98** [MountainDash/nonebot-plugin-send-anything-anywhere#70]
目前在整体框架层面最急切的需求是“消息回执”功能 #69 #65 。

简单来说就是在调用 send 函数后返回一个消息凭据，通过个消息凭据可以完成：
- 撤回发送的这条消息
- 修改发送的这条消息（未确定）
- 引用/回复 这条消息

将会提供这样的api：
```python
msg_receipt = await msg.send()

# 撤回这条消息
await msg_receipt.revoke()

# 生成回复这条消息的 Reply message_segment
reply_message_segment_factory = Reply(msg_receipt)

# 得到 send 的原始返回值
returned_val =  msg_receipt.raw
```

TBD：
- 需要提供 序列化/反序列化 吗

**Comment by canxin121** [comment]
序列化和反序列化应该是比较需要的,方便持久储存和撤回别人的消息之类的

**Comment by felinae98** [comment]
> 序列化和反序列化应该是比较需要的,方便持久储存和撤回别人的消息之类的

这里牵扯到一个问题是，撤回消息需要个 bot 实例，但是序列化和反序列化不能序列化这个 bot 实例，如果在多个 bot 存在的场景下自动选择发送这个消息的 bot 可能是困难的。

“撤回别人发的消息”超出了 saa 的设计初衷了，可能别的插件可以做到这一点

**Comment by canxin121** [comment]
> > 序列化和反序列化应该是比较需要的,方便持久储存和撤回别人的消息之类的
> 
> 这里牵扯到一个问题是，撤回消息需要个 bot 实例，但是序列化和反序列化不能序列化这个 bot 实例，如果在多个 bot 存在的场景下自动选择发送这个消息的 bot 可能是困难的。
> 
> “撤回别人发的消息”超出了 saa 的设计初衷了，可能别的插件可以做到这一点

感觉可以记录bot的self_id和platform然后去select对应的bot，然后撤回别人的消息是举个例子来具体的使用receipt.message_id，这里saa只需要给receipt一个统一名字的属性,message_id，方便提取
