### ISSUE TITLE
关于图片发送

### ISSUE THREAD

**Issue by lancer-wang** [MountainDash/nonebot-plugin-send-anything-anywhere#90]
img_ur 为我本地图片路径 如 /home/11.jpg
img_al = Image(img_ur)
img_al.send()

报错，提示 aiohttp.client_exceptions.InvalidURL:/home/11.jpg

但是我看代码里面是可以填路径的
![image](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/69783837/295cf3f3-09a3-42b5-8653-59b5bba3fb5b)

**Comment by ssttkkl** [comment]
猜你想要：
`img_al = Image(Path(img_ur))`

**Comment by lancer-wang** [comment]
> 猜你想要： `img_al = Image(Path(img_ur))`

emmmm
