### ISSUE TITLE
send_to 主动发送应该怎么用？

### ISSUE THREAD

**Issue by lancer-wang** [MountainDash/nonebot-plugin-send-anything-anywhere#99]
```    
    enable_auto_select_bot()
    for qq_group in read_qq_groups:
        target = TargetQQGroup(group_id=qq_group)
        msg_builder = MessageFactory([
            Text("今日60S读世界已送达\n"),Image(msg)
        ])
        await msg_builder.send_to(target)
```
这么写提示找不到bot
发到qq群

**Comment by AzideCupric** [comment]
能附带一下报错信息吗

**Comment by AzideCupric** [comment]
以及使用的adapter之类的可能有关的环境

**Comment by lancer-wang** [comment]
> 能附带一下报错信息吗

```  
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_saa/utils/types.py", line 307, in send_to
    bot = get_bot(target)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_saa/utils/auto_select_bot.py", line 84, in get_bot
    raise NoBotFound()
  nonebot_plugin_saa.utils.exceptions.NoBotFound
```

**Comment by AzideCupric** [comment]
适配器用的什么，gocq或者是red

**Comment by lancer-wang** [comment]
> 适配器用的什么，gocq或者是red

用的是red

**Comment by AzideCupric** [comment]
目前的话在nb运行期间red发生账号变动的话会导致saa找不到Bot，建议是重启一下nb，未来可能会修复这个问题

**Comment by lancer-wang** [comment]
> 目前的话在nb运行期间red发生账号变动的话会导致saa找不到Bot，建议是重启一下nb，未来可能会修复这个问题

我现在是一个gocq 一个 Chronocat
会不会是和这个有关

**Comment by AzideCupric** [comment]
应该没有关系，因为我单用red也有这个问题（

**Comment by lancer-wang** [comment]
> 应该没有关系，因为我单用red也有这个问题（

那nb应该怎么重启？

**Comment by AzideCupric** [comment]
就关掉插件这边然后重新运行呗

**Comment by lancer-wang** [comment]
> 就关掉插件这边然后重新运行呗

我之前是重启机器人，我再试试

**Comment by lancer-wang** [comment]
> 重启一下nb

![image](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere/assets/69783837/285a470a-54ff-4589-bb86-0c0053f3b5af)
重启机器人之后，还是这样

**Comment by AzideCupric** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/275726221-285a470a-54ff-4589-bb86-0c0053f3b5af.png) 重启机器人之后，还是这样

这句话里的 **机器人** 是指哪一边

**Comment by lancer-wang** [comment]
> > ![image](https://user-images.githubusercontent.com/69783837/275726221-285a470a-54ff-4589-bb86-0c0053f3b5af.png) 重启机器人之后，还是这样
> 
> 这句话里的 **机器人** 是指哪一边

gocq  Chronocat nonebot 都重启了

**Comment by lancer-wang** [comment]
> > > ![image](https://user-images.githubusercontent.com/69783837/275726221-285a470a-54ff-4589-bb86-0c0053f3b5af.png) 重启机器人之后，还是这样
> > 
> > 
> > 这句话里的 **机器人** 是指哪一边
> 
> gocq Chronocat nonebot 都重启了

成功了
```
abot = nonebot.get_bot()
await msg_builder.send_to(target,abot)
```

**Comment by lancer-wang** [comment]
> > > > ![image](https://user-images.githubusercontent.com/69783837/275726221-285a470a-54ff-4589-bb86-0c0053f3b5af.png) 重启机器人之后，还是这样
> > > 
> > > 
> > > 这句话里的 **机器人** 是指哪一边
> > 
> > 
> > gocq Chronocat nonebot 都重启了
> 
> 成功了
> 
> ```
> abot = nonebot.get_bot()
> await msg_builder.send_to(target,abot)
> ```

这么看的话，enable_auto_select_bot() 没有生效，不知道为什么

**Comment by AzideCupric** [comment]
其实这样就不是自动选择bot了
是最后重启的nonebot吗，要不加个群吧 868610060
